// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Mdl2Tool
{
    public class TemplarianItems
    {

        [JsonProperty("items")]
        public List<TemplarianClass> Items { get; set; }
    }

    public class TemplarianClass
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("keywords")]
        public List<string> Keywords { get; set; }
    }

}
